name: Deploy to GitHub Pages

on:
  # Deploy on push to main branch
  push:
    branches: [main]
  # Allow manual deployment
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
          
      - name: Install dependencies
        run: |
          cd client
          npm ci --prefer-offline --no-audit
          
      - name: Build for production
        run: |
          cd client
          npm run build
        env:
          NODE_ENV: production
          GITHUB_ACTIONS: true
          
      - name: Copy 404.html for SPA support
        run: |
          cp client/dist/index.html client/dist/404.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true  # Automatically enable GitHub Pages if not already enabled
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist

  # Deployment job
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4