name: Fix CloudFront Function

on:
  workflow_dispatch:

jobs:
  fix-function:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy CloudFront Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          # Check if function exists
          echo "Checking for existing CloudFront functions..."
          aws cloudfront list-functions --query 'FunctionList.Items[*].[Name,FunctionMetadata.Stage]' --output table
          
          # Create or update the function
          FUNCTION_NAME="6v-simulator-index-rewrite"
          FUNCTION_CODE='function handler(event) {
              var request = event.request;
              var uri = request.uri;
              
              // Check if the URI has a file extension
              if (!uri.includes(".")) {
                  // If no extension, serve index.html
                  request.uri = "/index.html";
              }
              
              return request;
          }'
          
          # Check if function exists
          if aws cloudfront describe-function --name "$FUNCTION_NAME" 2>/dev/null; then
              echo "Function exists, updating..."
              ETAG=$(aws cloudfront describe-function --name "$FUNCTION_NAME" --query 'ETag' --output text)
              
              aws cloudfront update-function \
                --name "$FUNCTION_NAME" \
                --if-match "$ETAG" \
                --function-config "{\"Comment\":\"SPA index rewrite\",\"Runtime\":\"cloudfront-js-2.0\"}" \
                --function-code "$FUNCTION_CODE"
              
              # Publish the function
              ETAG=$(aws cloudfront describe-function --name "$FUNCTION_NAME" --stage DEVELOPMENT --query 'ETag' --output text)
              aws cloudfront publish-function \
                --name "$FUNCTION_NAME" \
                --if-match "$ETAG"
          else
              echo "Creating new function..."
              aws cloudfront create-function \
                --name "$FUNCTION_NAME" \
                --function-config "{\"Comment\":\"SPA index rewrite\",\"Runtime\":\"cloudfront-js-2.0\"}" \
                --function-code "$FUNCTION_CODE"
              
              # Publish the function
              ETAG=$(aws cloudfront describe-function --name "$FUNCTION_NAME" --stage DEVELOPMENT --query 'ETag' --output text)
              aws cloudfront publish-function \
                --name "$FUNCTION_NAME" \
                --if-match "$ETAG"
          fi
          
          echo "Function ARN for association:"
          aws cloudfront describe-function --name "$FUNCTION_NAME" --query 'FunctionSummary.FunctionMetadata.FunctionARN' --output text