name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Delete preview from S3
        run: |
          aws s3 rm s3://${{ secrets.PR_PREVIEW_BUCKET_NAME }}/pr-${{ github.event.pull_request.number }}/ --recursive
          echo "✅ Deleted preview files for PR #${{ github.event.pull_request.number }}"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.PR_PREVIEW_DISTRIBUTION_ID }} \
            --paths "/pr-${{ github.event.pull_request.number }}/*" \
            --query 'Invalidation.Id' \
            --output text
          echo "✅ CloudFront cache invalidated"

      - name: Comment on PR about cleanup
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const was_merged = context.payload.pull_request.merged;
            
            const emoji = was_merged ? '🎉' : '🧹';
            const message = was_merged ? 'This PR has been merged!' : 'This PR has been closed.';
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `### ${emoji} Preview Deployment Cleaned Up
              
              ${message} The preview deployment for PR #${pr_number} has been removed.
              
              Thank you for your contribution to the 6-vertex model simulator!`
            });