name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Remove PR Preview from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          aws s3 rm s3://6v-simulator-pr-previews/pr-${PR_NUMBER}/ --recursive
      
      - name: Invalidate CloudFront
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          aws cloudfront create-invalidation \
            --distribution-id E1DZ4HUUOSPRK5 \
            --paths "/pr-${PR_NUMBER}/*"
      
      - name: Comment PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            
            const comment = `## 🧹 PR Preview Cleaned Up
            
            The preview for PR #${prNumber} has been removed.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });