name: Setup AWS Infrastructure

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check AWS Account
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "Checking AWS account identity..."
          aws sts get-caller-identity
          
      - name: Create S3 Buckets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "Creating production bucket..."
          aws s3api create-bucket \
            --bucket 6v-allison-la-production \
            --region us-east-1 2>/dev/null || echo "Bucket creation failed or already exists"
          
          echo "Waiting for bucket to be available..."
          sleep 5
          
          echo "Creating PR preview bucket..."
          aws s3api create-bucket \
            --bucket 6v-allison-la-pr-previews \
            --region us-east-1 2>/dev/null || echo "Bucket creation failed or already exists"
          
          echo "Waiting for buckets to be available..."
          sleep 5
          
          echo "Checking if buckets exist..."
          aws s3api head-bucket --bucket 6v-allison-la-production 2>/dev/null && echo "Production bucket exists" || echo "Production bucket does not exist"
          aws s3api head-bucket --bucket 6v-allison-la-pr-previews 2>/dev/null && echo "PR preview bucket exists" || echo "PR preview bucket does not exist"
          
          echo "Configuring buckets for static website hosting..."
          aws s3api put-bucket-website \
            --bucket 6v-allison-la-production \
            --website-configuration '{"IndexDocument":{"Suffix":"index.html"},"ErrorDocument":{"Key":"404.html"}}' 2>/dev/null || echo "Could not configure production bucket website"
          
          aws s3api put-bucket-website \
            --bucket 6v-allison-la-pr-previews \
            --website-configuration '{"IndexDocument":{"Suffix":"index.html"},"ErrorDocument":{"Key":"404.html"}}' 2>/dev/null || echo "Could not configure PR preview bucket website"
          
          echo "Setting bucket policies for CloudFront access..."
          # We'll add policies after creating CloudFront OAC
          
      - name: List Available Resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "Listing S3 buckets..."
          aws s3api list-buckets
          
          echo "Listing CloudFront distributions..."
          aws cloudfront list-distributions --query 'DistributionList.Items[*].[Id,DomainName,Aliases.Items[0]]' --output table || echo "No distributions found"